# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 03:48
# pylint: skip-file

import django.contrib.gis.db.models.fields
import django.db.models

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    
    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=1024)),
                ('generator', models.CharField(max_length=1024)),
                ('created', models.DateTimeField()),
                ('generated_at', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('recorded', models.DateTimeField()),
                ('properties', models.JSONField()),
            ],
        ),
    ]
