# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 21:50
# pylint: skip-file

import django.db.models
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0023_auto_20170731_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='performance_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
