# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 16:02


import django.db.models
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('passive_data_kit', '0073_dataserver_request_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='configuration_json',
            field=models.JSONField(),
        ),
    ]
