# pylint: skip-file
# Generated by Django 5.2.10 on 2026-03-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0101_appconfigurationversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBundleProcessingTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_id', models.BigIntegerField(db_index=True)),
                ('bundle_trace_id', models.CharField(db_index=True, max_length=36)),
                ('data_point_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(db_index=True, max_length=64)),
                ('bundle_recorded', models.DateTimeField(blank=True, null=True)),
                ('point_count', models.IntegerField(blank=True, null=True)),
                ('encrypted', models.BooleanField(default=False)),
                ('compression', models.CharField(blank=True, default='', max_length=128)),
                ('error_class', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created', 'pk'],
                'indexes': [
                    models.Index(fields=['bundle_id', 'created'], name='passive_dat_bundle__d49343_idx'),
                    models.Index(fields=['bundle_trace_id'], name='passive_dat_bundle__9d54dd_idx'),
                    models.Index(fields=['status', 'created'], name='passive_dat_status_5e7a16_idx'),
                    models.Index(fields=['data_point_id'], name='passive_dat_data_po_e230d0_idx'),
                ],
            },
        ),
    ]
