# pylint: skip-file

# Generated by Django 5.2.12 on 2026-04-10 02:08

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0101_appconfigurationversion_and_more'),
    ]

    operations = []

    if django.VERSION[0] >= 4:
        operations.extend([
            migrations.RenameIndex(
                model_name='appconfiguration',
                new_name='passive_dat_is_vali_081dc6_idx',
                old_fields=('is_valid', 'is_enabled'),
            ),
            migrations.RenameIndex(
                model_name='appconfiguration',
                new_name='passive_dat_is_vali_dc6c72_idx',
                old_fields=('is_valid', 'is_enabled', 'evaluate_order'),
            ),
            migrations.RenameIndex(
                model_name='datapoint',
                new_name='passive_dat_created_1fc60c_idx',
                old_fields=('created', 'source_reference'),
            ),
            migrations.RenameIndex(
                model_name='datapoint',
                new_name='passive_dat_recorde_a757ed_idx',
                old_fields=('recorded', 'generator_definition'),
            ),
            migrations.RemoveField(
                model_name='appconfigurationversion',
                name='created',
            )
        ])
        
    operations.extend([
        migrations.AlterField(
            model_name='databundle',
            name='properties',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='properties',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='performance_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcealert',
            name='alert_details',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='reportdestination',
            name='parameters',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='parameters',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='reportjobbatchrequest',
            name='parameters',
            field=models.JSONField(),
        ),
    ])
