# pylint: skip-file
# Generated by Django 5.2.14 on 2026-05-25 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('passive_data_kit', '0102_databundleprocessingtrace'),
        ('passive_data_kit', '0102_rename_appconfiguration_is_valid_is_enabled_passive_dat_is_vali_081dc6_idx_and_more'),
    ]

    operations = [
    ]
