# pylint: skip-file
# Generated by Django 5.2.14 on 2026-05-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0103_merge_20260525_1539'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='databundleprocessingtrace',
            new_name='passive_dat_bundle__8fa211_idx',
            old_name='passive_dat_bundle__d49343_idx',
        ),
        migrations.RenameIndex(
            model_name='databundleprocessingtrace',
            new_name='passive_dat_bundle__62befa_idx',
            old_name='passive_dat_bundle__9d54dd_idx',
        ),
        migrations.RenameIndex(
            model_name='databundleprocessingtrace',
            new_name='passive_dat_status_a34903_idx',
            old_name='passive_dat_status_5e7a16_idx',
        ),
        migrations.RenameIndex(
            model_name='databundleprocessingtrace',
            new_name='passive_dat_data_po_3f532d_idx',
            old_name='passive_dat_data_po_e230d0_idx',
        ),
        migrations.AddField(
            model_name='databundle',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
