# pylint: skip-file
# Generated by Django 5.2.14 on 2026-05-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0104_rename_passive_dat_bundle__d49343_idx_passive_dat_bundle__8fa211_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='identifier',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
