# Generated by Django 5.2.17 on 2026-08-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0105_alter_datafile_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
