# pylint: skip-file
# Generated by Django 5.2.17 on 2026-09-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0106_datasource_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='secondary_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
    ]
