# pylint: skip-file
# Generated by Django 5.2.17 on 2026-09-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0107_alter_datapoint_secondary_identifier'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datapoint',
            index=models.Index(fields=['source_reference', 'generator_definition', 'created', 'recorded'], name='passive_dat_source__9f60f8_idx'),
        ),
    ]
