# pylint: skip-file
# Generated by Django 5.2.17 on 2026-10-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0108_datapoint_passive_dat_source__9f60f8_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datageneratordefinition',
            name='generator_identifier',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='datageneratordefinition',
            name='name',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
