# pylint: skip-file
# Generated by Django 5.2.17 on 2026-10-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0109_alter_datageneratordefinition_generator_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcereference',
            name='source',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
