# pylint: skip-file
# Generated by Django 5.2.17 on 2026-10-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0110_alter_datasourcereference_source'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='datapoint',
            name='passive_dat_source__9f60f8_idx',
        ),
        migrations.AddIndex(
            model_name='datapoint',
            index=models.Index(fields=['generator_definition', 'source_reference', 'created', 'recorded'], name='passive_dat_generat_2564da_idx'),
        ),
        migrations.AddIndex(
            model_name='datapoint',
            index=models.Index(fields=['generator_definition', 'source_reference', 'created'], name='passive_dat_generat_06761d_idx'),
        ),
        migrations.AddIndex(
            model_name='datapoint',
            index=models.Index(fields=['generator_definition', 'source_reference', 'recorded'], name='passive_dat_generat_be3d2a_idx'),
        ),
    ]
